import { defineConfig } from 'vitest/config'

// Tests run against the decks directly, with no app framework in the way —
// just Vite's tsconfig path resolution (@hull/* etc.) and a node environment.
// Database tests use in-memory PGlite (see hull/health/service.test.ts), so the
// whole suite runs anywhere — your laptop, a Claude Code session, CI — with no
// Postgres, no Docker, no network.
export default defineConfig({
  resolve: { tsconfigPaths: true },
  test: {
    environment: 'node',
    include: ['src/**/*.test.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      // text for the terminal, lcov for diff-cover (the PR diff gate),
      // json-summary for tooling, html for a browsable report.
      reporter: ['text', 'text-summary', 'lcov', 'json-summary', 'html'],
      reportsDirectory: './coverage',
      // Measure every deck's source, then carve out what shouldn't be gated.
      include: ['src/**/*.{ts,tsx}'],
      // The ignore list keeps the global threshold ambitious by excluding code
      // that isn't ours to test or carries no logic. Logic lives in service.ts
      // files and views — those stay measured.
      exclude: [
        'src/**/*.test.{ts,tsx}', // tests themselves
        'src/**/*.d.ts',
        'src/routeTree.gen.ts', // generated by tsr
        'src/router.tsx', // framework wiring
        'src/routes/**', // route definitions — thin TanStack glue
        'src/**/server.ts', // createServerFn doors; logic belongs in service.ts
        'src/**/cli.ts', // CLI doors; logic belongs in service.ts/runtime.ts
        'src/**/test-db.ts', // test-only DB harness, not shipped logic
        'src/hull/db/client.ts', // live Postgres connection wiring
        'src/rigging/components/ui/**', // vendored shadcn primitives
        'src/rigging/lib/utils.ts', // vendored shadcn cn() helper
        'src/**/schema.ts', // drizzle table declarations — data, not logic
        'src/**/*.config.{ts,js}',
        'src/.claude/**',
      ],
      // The global gate. Ambitious on purpose — see the ignore list above.
      // Diff coverage (changed lines) is enforced separately by scripts/coverage-diff.
      thresholds: {
        lines: 90,
        branches: 90,
        functions: 90,
        statements: 90,
      },
    },
  },
})
